In [593]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [594]:
dataset = pd.read_csv('IMDB_Review.tsv', delimiter = '\t', quoting = 3)

#Text cleaning

In [595]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
f = []
for x in range (0,1000):
  result = re.sub( '[^a-zA-Z]',  ' ',  dataset['Review'][x] )
  result = result.lower()
  result = result.split()
  P = PorterStemmer()
  z = stopwords.words('english')
  z.remove('not')
  result = [P.stem(y) for y in result if not y in set(z)]
  result = ' '.join(result)
  f.append(result)



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [596]:
from sklearn.feature_extraction.text import CountVectorizer
C = CountVectorizer(max_features = 1200)
X = C.fit_transform(f).toarray()
Y = dataset.iloc[:, 1].values

#Splitting the dataset

In [597]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.15, random_state = 0)

#Training the Logistic Regression model

In [598]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)
LR.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [599]:
Y_P1 = LR.predict(X_test)
print(Y_test)
print(Y_P1)

[0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0
 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 1 1 1 1
 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0]
[0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0
 0 0 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 1 1 0
 0 0 0 1 0 1 0 1 1 0 1 1 1 0 1 1]


In [600]:
#print(np.concatenate((Y_P1.reshape(len(Y_P1),1), Y_test.reshape(len(Y_test),1)),1))

Confusion Matrix & Accuracy Score

In [601]:
from sklearn.metrics import confusion_matrix, accuracy_score
CM1 = confusion_matrix(Y_test, Y_P1)
print(CM1, "\n")
accuracy_score(Y_test, Y_P1)

[[34 11]
 [ 8 37]] 



0.7888888888888889

#Training the Naive Bayes model

In [602]:
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()
NB.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [603]:
Y_P2 = NB.predict(X_test)
#print(np.concatenate((Y_P2.reshape(len(Y_P2),1), Y_test.reshape(len(Y_test),1)),1))

Confusion Matrix & Accuracy Score

In [604]:
from sklearn.metrics import confusion_matrix, accuracy_score
CM2 = confusion_matrix(Y_test, Y_P2)
print(CM2)
accuracy_score(Y_test, Y_P2)

[[24 21]
 [ 3 42]]


0.7333333333333333

#Training the SVM model

In [605]:
from sklearn.svm import SVC
SV = SVC(kernel = 'linear', random_state = 0)
SV.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [606]:
Y_P3 = SV.predict(X_test)
#print(np.concatenate((Y_P3.reshape(len(Y_P3),1), Y_test.reshape(len(Y_test),1)),1))

Confusion Matrix & Accuracy Score

In [607]:
from sklearn.metrics import confusion_matrix, accuracy_score
CM3 = confusion_matrix(Y_test, Y_P3)
print(CM3, "\n")
accuracy_score(Y_test, Y_P3)

[[36  9]
 [ 5 40]] 



0.8444444444444444

#Training the Random Forest Classification model

In [608]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
RF.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [609]:
Y_P4 = RF.predict(X_test)
#print(np.concatenate((Y_P4.reshape(len(Y_P4),1), Y_test.reshape(len(Y_test),1)),1))

Confusion Matrix & Accuracy Score

In [610]:
from sklearn.metrics import confusion_matrix, accuracy_score
CM4 = confusion_matrix(Y_test, Y_P4)
print(CM4)
accuracy_score(Y_test, Y_P4)

[[38  7]
 [14 31]]


0.7666666666666667

Single Review Example

In [611]:
new = 'This restaurant is okay but I did not like the food'
new = re.sub('[^a-zA-Z]', ' ', new)
new = new.lower()
new = new.split()
P = PorterStemmer()
z = stopwords.words('english')
z.remove('not')
new = [P.stem(word) for word in new if not word in set(z)]
new = ' '.join(new)
f1 = [new]

new_X = C.transform(f1).toarray()
new_y_P = SV.predict(new_X)
print(new_y_P)

[0]
